#Problem 45
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	T_n = n(n + 1)/2	1,3,6,10,15,…
#Pentagonal	 	P_n = n(3n − 1)/2	1,5,12,22,35,…
#Hexagonal	 	H_n = n(2n − 1)	 	1,6,15,28,45,…

#It can be verified that T_285 = P_165 = H_143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# A number x is Pentagonal if n = (1 + sqrt(1+24x)) / 6 is an integer and is Hexagonal if n = (1 + sqrt(1 + 8x)) / 4 is an integer.

import math

def is_pentagonal(x):
    n = (1 + math.sqrt(1 + 24*x)) / 6
    return n == int(n)

def is_hexagonal(x):
    n = (1 + math.sqrt(1 + 8*x)) / 4
    return n == int(n)

tri_nums = [n*(n + 1)//2 for n in range(286,100000)] #We can increase range when needed

for num in tri_nums:
    if is_pentagonal(num) and is_hexagonal(num):
        print(num)
        break
