#Problem 61
#Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate
#(polygonal) numbers and are generated by the following formulas:

#Triangle	 	P_3,n =n⁢(n + 1)/2	1,3,6,10,15,…
#Square	 	        P_4,n =n^2	 	1,4,9,16,25,…
#Pentagonal	 	P_5,n =n(3⁢n − 1)/2	1,5,12,22,35,…
#Hexagonal	 	P_6,n =n⁢(2⁢n − 1)	1,6,15,28,45,…
#Heptagonal	 	P_7,n =n(5⁢n − 3)/2	1,7,18,34,55,…
#Octagonal	 	P_8,n =n(3⁢n − 2)        1,8,21,40,65,…
#The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

#The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
#Each polygonal type: triangle (P_3,127 = 8128), square (P4,91 = 8281), and pentagonal (P5,44 = 2882), is represented by a different number in the set.
#This is the only set of 4-digit numbers with this property.
#Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type:
#triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

from itertools import permutations

tri_nums = [n*(n+1)//2 for n in range(150) if n*(n+1)//2 >= 1000 and n*(n+1)//2 < 10000]
sqr_nums = [n*n for n in range(100) if n*n >= 1000 and n*n < 10000]
pen_nums = [n*(3*n - 1)//2 for n in range(100) if n*(3*n - 1)//2 >= 1000 and n*(3*n - 1)//2 < 10000]
hex_nums = [n*(2*n - 1) for n in range(100) if n*(2*n - 1) >= 1000 and n*(2*n - 1) < 10000]
hep_nums = [n*(5*n - 3)//2 for n in range(100) if n*(5*n - 3)//2 >= 1000 and n*(5*n - 3)//2 < 10000]
oct_nums = [n*(3*n - 2) for n in range(100) if n*(3*n - 2) >= 1000 and n*(3*n - 2) < 10000]

def func(list_):
    nums1, nums2, nums3, nums4, nums5, nums6 = list_
    pairs = []

    for num in nums1:
        for num2 in nums2:
            if str(num)[2:] == str(num2)[:2]:
                pairs.append((num, num2))

    triples = []

    for num1, num2 in pairs:
        for num3 in nums3:
            if str(num2)[2:] == str(num3)[:2]:
                triples.append((num1, num2, num3))

    quadruples = []

    for num1, num2, num3 in triples:
        for num4 in nums4:
            if str(num3)[2:] == str(num4)[:2]:
                quadruples.append((num1, num2, num3, num4))

    quintuples = []

    for num1, num2, num3, num4 in quadruples:
        for num5 in nums5:
            if str(num4)[2:] == str(num5)[:2]:
                quintuples.append((num1, num2, num3, num4, num5))

    for num1, num2, num3, num4, num5 in quintuples:
        for num6 in nums6:
            if str(num5)[2:] == str(num6)[:2] and str(num6)[2:] == str(num1)[:2]:
                return (num1, num2, num3, num4, num5, num6)

for permutation in permutations([tri_nums, sqr_nums, pen_nums, hex_nums, hep_nums, oct_nums]):
    cycle = func(permutation)
    if cycle != None:
        print(cycle)
        print(sum(cycle))




    
