#Problem 29
#How many distinct terms are in the sequence generated by a**b for 2 <= a, b <= 100?

set_of_distincts = set()

for a in range(2,101):
    for b in range(2,101):
        set_of_distincts.add(a**b)

print(len(set_of_distincts))

