#Problem 44
#Pentagonal numbers are generated by the formula, P_n = n(3⁢n − 1)/2. The first ten pentagonal numbers are:
#1,5,12,22,35,51,70,92,117,145,…

#It can be seen that P_4 + P_7 = 22 +70 = 92 = P_8. However, their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and D = |P_k - P_j| is minimised; what is the value of D?

#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Pent_nums = [n*(3*n - 1)//2 for n in range(1,10001)]   #We can just increase the range until we get our desired result
Pent_nums_set = set(Pent_nums)  #To make our search easier

D = float('inf') #Some large number

for j in range(10000):
    for k in range(j + 1, 10000):
        sum_ = Pent_nums[k] + Pent_nums[j]
        diff = Pent_nums[k] - Pent_nums[j]
        
        if diff >= D:
            # No need to continue with larger differences
            break
        
        if (sum_ in Pent_nums_set) and (diff in Pent_nums_set):
            if diff < D:
                D = diff

print(D)
