#Problem 12
#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 28.
#What is the value of the first triangle number to have over five hundred divisors?

from NumberOfFactors import numberOfFactors

k = 1

while True:
    # Compute divisor count using the coprime trick
    if k % 2 == 0:
        a = numberOfFactors(k // 2)
        b = numberOfFactors(k + 1)
    else:
        a = numberOfFactors(k)
        b = numberOfFactors((k + 1) // 2)

    if a * b > 500:
        print(k * (k + 1) // 2)
        break

    k += 1
